# Generated by Django 3.2.8 on 2021-10-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BL0G', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overview',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
