# Generated by Django 3.2.8 on 2021-10-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, default=None, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
